#!/bin/bash
# ════════════════════════════════════════════════════════════════════
#  KAT PHARMA — Hetzner Server Setup
#  Installs IB Gateway + IBC (auto-login) + systemd services
#  Run once as root: bash setup_ibgateway.sh
#
#  After this runs, IB Gateway starts automatically on boot,
#  logs in by itself, and executor.py connects to it locally.
#  Your laptop is never needed.
# ════════════════════════════════════════════════════════════════════

set -e

# ── Your IBKR credentials — fill these in ───────────────────────────
IBKR_USER="YOUR_IBKR_USERNAME"
IBKR_PASS="YOUR_IBKR_PASSWORD"
IBKR_MODE="live"          # "live" or "paper"
IBKR_PORT="4001"          # 4001=live gateway, 4002=paper gateway

# ── Paths ────────────────────────────────────────────────────────────
IBC_DIR="/opt/ibc"
GW_DIR="/root/Jts/ibgateway/1037"    # IB Gateway actual default install path
KAT_DIR="/root/katherina-trader/pharma"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  KAT — Hetzner IB Gateway Setup"
echo "════════════════════════════════════════════════════════════════"
echo ""

# ── 1. System deps ───────────────────────────────────────────────────
echo "→ Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq \
    xvfb \
    x11vnc \
    openjdk-17-jre \
    wget \
    unzip \
    curl \
    python3-pip \
    expect

pip install ib_insync schedule --break-system-packages -q

echo "✓ Dependencies installed"

# ── 2. Download IB Gateway ───────────────────────────────────────────
echo "→ Downloading IB Gateway (stable)..."
mkdir -p "$GW_DIR"

wget -q -O /tmp/ibgateway_install.sh \
  "https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh"

chmod +x /tmp/ibgateway_install.sh

# Silent install — pipe blank answers for all prompts
echo -e "\n\n\n\n\n\n\n\n" | bash /tmp/ibgateway_install.sh -c

echo "✓ IB Gateway installed → $GW_DIR"

# ── 3. Download IBC ──────────────────────────────────────────────────
echo "→ Downloading IBC (auto-login controller)..."
mkdir -p "$IBC_DIR"

IBC_VERSION="3.19.1"
wget -q -O /tmp/ibc.zip \
  "https://github.com/IbcAlpha/IBC/releases/download/${IBC_VERSION}/IBCLinux-${IBC_VERSION}.zip"

unzip -q -o /tmp/ibc.zip -d "$IBC_DIR"
chmod +x "$IBC_DIR"/*.sh "$IBC_DIR"/scripts/*.sh 2>/dev/null || true

echo "✓ IBC installed → $IBC_DIR"

# ── 4. Configure IBC ────────────────────────────────────────────────
echo "→ Writing IBC config..."
cat > "$IBC_DIR/config.ini" << IBCCONFIG
# IBC Configuration — auto-generated by KAT setup
[IBCSettings]
FIX=no
IbLoginId=$IBKR_USER
IbPassword=$IBKR_PASS
TradingMode=$IBKR_MODE
IbDir=$GW_DIR
StoreSettingsOnServer=no
MinimizeMainWindow=yes
ExistingSessionDetectedAction=primaryoverride
AcceptIncomingConnectionAction=accept
ShowAllTrades=no
ForceTwsApiPort=$IBKR_PORT
ReadOnlyLogin=no
ReadOnlyApi=no
AcceptNonBrokerageAccountWarning=yes
AutoLogoffTime=
AutoRestartTime=11:59 PM
LogComponents=never
IBCCONFIG

echo "✓ IBC configured"

# ── 5. Startup script ────────────────────────────────────────────────
echo "→ Writing gateway startup script..."
cat > /usr/local/bin/kat_gateway_start.sh << 'STARTSCRIPT'
#!/bin/bash
# Start Xvfb virtual display then IB Gateway via IBC
export DISPLAY=:1

# Kill any existing Xvfb
pkill Xvfb 2>/dev/null || true
sleep 1

# Start virtual display
Xvfb :1 -screen 0 1024x768x24 -nolisten tcp &
XVFB_PID=$!
echo "Xvfb started (pid $XVFB_PID)"
sleep 2

# Launch IB Gateway via IBC
cd /opt/ibc
bash /opt/ibc/gatewaystart.sh \
    /opt/ibc/config.ini \
    /root/Jts/ibgateway/1037 \
    latest \
    >> /var/log/kat_ibgateway.log 2>&1 &

echo "IB Gateway starting..."
STARTSCRIPT

chmod +x /usr/local/bin/kat_gateway_start.sh

# ── 6. Health check script ───────────────────────────────────────────
cat > /usr/local/bin/kat_gateway_check.sh << 'CHECKSCRIPT'
#!/usr/bin/env python3
"""Check if IB Gateway is reachable on localhost."""
import sys
try:
    from ib_insync import IB, util
    util.startLoop()
    ib = IB()
    ib.connect("127.0.0.1", 4001, clientId=99, timeout=10)
    acct = ib.managedAccounts()
    print(f"✓ IB Gateway alive  account={acct}")
    ib.disconnect()
    sys.exit(0)
except Exception as e:
    print(f"✗ IB Gateway not reachable: {e}")
    sys.exit(1)
CHECKSCRIPT

chmod +x /usr/local/bin/kat_gateway_check.sh

# ── 7. Watchdog — restarts gateway if it dies ───────────────────────
cat > /usr/local/bin/kat_gateway_watchdog.sh << 'WATCHDOG'
#!/bin/bash
# Watchdog: check every 5 min, restart gateway if down
LOG="/var/log/kat_watchdog.log"
echo "[$(date)] Watchdog check..." >> "$LOG"

if python3 /usr/local/bin/kat_gateway_check.sh >> "$LOG" 2>&1; then
    echo "[$(date)] Gateway OK" >> "$LOG"
else
    echo "[$(date)] Gateway DOWN — restarting..." >> "$LOG"
    /usr/local/bin/kat_gateway_start.sh >> "$LOG" 2>&1
    sleep 30
    python3 /usr/local/bin/kat_gateway_check.sh >> "$LOG" 2>&1 \
        && echo "[$(date)] Gateway recovered" >> "$LOG" \
        || echo "[$(date)] Gateway still down after restart" >> "$LOG"
fi
WATCHDOG

chmod +x /usr/local/bin/kat_gateway_watchdog.sh

# ── 8. Systemd service for IB Gateway ───────────────────────────────
echo "→ Creating systemd services..."

cat > /etc/systemd/system/kat-ibgateway.service << 'SERVICE'
[Unit]
Description=KAT IB Gateway (headless)
After=network.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/kat_gateway_start.sh
ExecStop=pkill -f ibgateway
Restart=on-failure
RestartSec=30
User=root
Environment=DISPLAY=:1

[Install]
WantedBy=multi-user.target
SERVICE

# ── 9. Systemd service for KAT executor (buy scan) ──────────────────
cat > /etc/systemd/system/kat-executor-buy.service << SERVICE
[Unit]
Description=KAT Pharma Executor — Buy Signal Scanner
After=kat-ibgateway.service
Requires=kat-ibgateway.service

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 $KAT_DIR/executor.py --buy
User=root
WorkingDirectory=$KAT_DIR
StandardOutput=append:/var/log/kat_executor.log
StandardError=append:/var/log/kat_executor.log
SERVICE

# Systemd timer: buy scan at 15:05 CET Mon-Fri
cat > /etc/systemd/system/kat-executor-buy.timer << 'TIMER'
[Unit]
Description=KAT Buy Scan — daily 15:05 CET

[Timer]
OnCalendar=Mon-Fri *-*-* 15:05:00 Europe/Zurich
Persistent=true
Unit=kat-executor-buy.service

[Install]
WantedBy=timers.target
TIMER

# T-1 sell service + timer
cat > /etc/systemd/system/kat-executor-t1.service << SERVICE
[Unit]
Description=KAT Pharma Executor — T-1 Sell (50%)
After=kat-ibgateway.service

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 $KAT_DIR/executor.py --t1
User=root
WorkingDirectory=$KAT_DIR
StandardOutput=append:/var/log/kat_executor.log
StandardError=append:/var/log/kat_executor.log
SERVICE

cat > /etc/systemd/system/kat-executor-t1.timer << 'TIMER'
[Unit]
Description=KAT T-1 Sell — daily 15:00 CET

[Timer]
OnCalendar=Mon-Fri *-*-* 15:00:00 Europe/Zurich
Persistent=true
Unit=kat-executor-t1.service

[Install]
WantedBy=timers.target
TIMER

# PDUFA exit service + timer
cat > /etc/systemd/system/kat-executor-exit.service << SERVICE
[Unit]
Description=KAT Pharma Executor — PDUFA Day Exit
After=kat-ibgateway.service

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 $KAT_DIR/executor.py --exit
User=root
WorkingDirectory=$KAT_DIR
StandardOutput=append:/var/log/kat_executor.log
StandardError=append:/var/log/kat_executor.log
SERVICE

cat > /etc/systemd/system/kat-executor-exit.timer << 'TIMER'
[Unit]
Description=KAT PDUFA Exit — daily 14:35 CET

[Timer]
OnCalendar=Mon-Fri *-*-* 14:35:00 Europe/Zurich
Persistent=true
Unit=kat-executor-exit.service

[Install]
WantedBy=timers.target
TIMER

# Watchdog timer — every 5 min
cat > /etc/systemd/system/kat-watchdog.service << 'SERVICE'
[Unit]
Description=KAT Gateway Watchdog

[Service]
Type=oneshot
ExecStart=/usr/local/bin/kat_gateway_watchdog.sh
User=root
SERVICE

cat > /etc/systemd/system/kat-watchdog.timer << 'TIMER'
[Unit]
Description=KAT Gateway Watchdog — every 5 min

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Unit=kat-watchdog.service

[Install]
WantedBy=timers.target
TIMER

# ── 10. Enable all services ──────────────────────────────────────────
echo "→ Enabling systemd services and timers..."
systemctl daemon-reload

systemctl enable kat-ibgateway.service
systemctl enable kat-executor-buy.timer
systemctl enable kat-executor-t1.timer
systemctl enable kat-executor-exit.timer
systemctl enable kat-watchdog.timer

systemctl start kat-watchdog.timer
systemctl start kat-executor-buy.timer
systemctl start kat-executor-t1.timer
systemctl start kat-executor-exit.timer

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✓ Setup complete"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  NEXT STEP — start IB Gateway now:"
echo ""
echo "    systemctl start kat-ibgateway"
echo "    sleep 30"
echo "    python3 /usr/local/bin/kat_gateway_check.sh"
echo ""
echo "  If gateway check passes, fire the buy:"
echo ""
echo "    cd $KAT_DIR && python3 executor.py --buy"
echo ""
echo "  Watch live logs:"
echo "    tail -f /var/log/kat_executor.log"
echo "    tail -f /var/log/kat_ibgateway.log"
echo "    tail -f /var/log/kat_watchdog.log"
echo ""
echo "  Check timers:"
echo "    systemctl list-timers kat-*"
echo ""
echo "  From here on — everything runs itself. No laptop needed."
echo ""
